require 'open-uri'
require 'nokogiri'
require 'pry'

require_relative './gameplay/game'
require_relative './gameplay/team'
require_relative './gameplay/pitcher'
require_relative './gameplay/seed'
require_relative './gameplay/scraper'
require_relative './gameplay/cli'